# Generated by Django 4.0.5 on 2022-06-11 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('company_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('company_type_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('company_type_name', models.CharField(max_length=200)),
                ('company_type_img', models.FileField(blank=True, null=True, upload_to='apps/static/assets/media/images/company_type')),
            ],
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('factory_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('factory_name', models.CharField(max_length=200)),
                ('factory_address', models.CharField(max_length=200)),
                ('factory_img', models.ImageField(blank=True, null=True, upload_to='apps/static/assets/media/images/factory')),
                ('company_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factory_company_fk', to='factory.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('machine_name', models.CharField(max_length=200)),
                ('machine_img', models.ImageField(blank=True, null=True, upload_to='apps/static/assets/media/images/machine')),
                ('factory_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine_factory_fk', to='factory.factory')),
            ],
        ),
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('machine_type_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('machine_type_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('server_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('server_name', models.CharField(max_length=200)),
                ('factory_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_company_fk', to='factory.factory')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('sensor_parent', models.CharField(max_length=200)),
                ('sensor_mac', models.CharField(max_length=200)),
                ('sensor_tag', models.CharField(max_length=200)),
                ('sensor_img', models.ImageField(blank=True, null=True, upload_to='apps/static/assets/media/images/sensor')),
                ('factory_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_factory_fk', to='factory.factory')),
                ('machine_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_machine_fk', to='factory.machine')),
                ('server_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_server_fk', to='factory.server')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_type_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine_type_fk', to='factory.machinetype'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_type_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_type_fk', to='factory.companytype'),
        ),
    ]
