# Generated by Django 4.0.3 on 2022-04-11 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('company_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('user_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('machine_name', models.CharField(max_length=200)),
                ('company_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine', to='factory.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('sensor_parent', models.CharField(max_length=200)),
                ('sensor_mac', models.CharField(max_length=200)),
                ('sensor_tag', models.CharField(max_length=200)),
                ('machine_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_machine_fk', to='factory.machine')),
            ],
        ),
    ]
