# Generated by Django 4.0.3 on 2022-04-12 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='user_fk',
        ),
    ]
