# Generated by Django 4.0.4 on 2022-05-12 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_remove_companyprofile_user_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='company_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_machine_fk', to='factory.companyprofile'),
        ),
    ]
