# Generated by Django 4.0.4 on 2022-05-13 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_sensor_company_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('server_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('server_name', models.CharField(max_length=200)),
                ('company_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_company_fk', to='factory.companyprofile')),
            ],
        ),
    ]
