# Generated by Django 4.0.4 on 2022-05-13 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0004_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='server_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_server_fk', to='factory.server'),
        ),
    ]
