# Generated by Django 4.0.4 on 2022-05-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0005_sensor_server_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='sensor_img',
            field=models.ImageField(blank=True, upload_to='%Y/%m/%d'),
        ),
    ]
