# Generated by Django 4.0.4 on 2022-05-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0006_sensor_sensor_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
