# Generated by Django 4.0.4 on 2022-05-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0007_alter_sensor_sensor_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_img',
            field=models.ImageField(blank=True, null=True, upload_to='apps/static/assets/media/images'),
        ),
    ]
