# Generated by Django 4.0.4 on 2022-05-26 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0008_alter_sensor_sensor_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='company_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine_company_fk', to='factory.companyprofile'),
        ),
    ]
