# Generated by Django 4.0.4 on 2022-05-26 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0009_alter_machine_company_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='company_fk',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='company_fk',
        ),
        migrations.RemoveField(
            model_name='server',
            name='company_fk',
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_img',
            field=models.ImageField(blank=True, null=True, upload_to='apps/static/assets/media/images'),
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('factory_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('factory_name', models.CharField(max_length=200)),
                ('factory_address', models.CharField(max_length=200)),
                ('factory_img', models.ImageField(blank=True, null=True, upload_to='apps/static/assets/media/images')),
                ('company_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factory_company_fk', to='factory.companyprofile')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='factory_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine_factory_fk', to='factory.factory'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='factory_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_factory_fk', to='factory.factory'),
        ),
        migrations.AddField(
            model_name='server',
            name='factory_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_company_fk', to='factory.factory'),
        ),
    ]
