# Generated by Django 4.0.4 on 2022-05-30 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0010_remove_machine_company_fk_remove_sensor_company_fk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('machine_type_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('machine_type_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_type_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine_type_fk', to='factory.machinetype'),
        ),
    ]
