# Generated by Django 4.0.4 on 2022-05-31 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0011_machinetype_machine_machine_type_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('company_type_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('company_type_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_type_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_type_fk', to='factory.companytype'),
        ),
    ]
