# Generated by Django 4.0.4 on 2022-05-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0012_companytype_companyprofile_company_type_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytype',
            name='company_type_img',
            field=models.ImageField(blank=True, null=True, upload_to='apps/static/assets/media/images/company_type'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='factory_img',
            field=models.ImageField(blank=True, null=True, upload_to='apps/static/assets/media/images/factory'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_img',
            field=models.ImageField(blank=True, null=True, upload_to='apps/static/assets/media/images/machine'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_img',
            field=models.ImageField(blank=True, null=True, upload_to='apps/static/assets/media/images/sensor'),
        ),
    ]
