# Generated by Django 4.0.4 on 2022-06-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0013_companytype_company_type_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytype',
            name='company_type_img',
            field=models.FileField(blank=True, null=True, upload_to='apps/static/assets/media/images/company_type'),
        ),
    ]
